# rust-toolchain.toml

# HoneyLink Rust Toolchain Configuration
# This file pins the Rust version and components for reproducible builds across all environments.

[toolchain]
# Lock to specific stable version for reproducibility
# Using Linux GNU toolchain for WSL/Linux native builds
channel = "1.89.0"

# Essential components for development and CI
components = [
    "clippy",      # Linter for catching common mistakes and enforcing best practices
    "rustfmt",     # Code formatter for consistent style
    "rust-src",    # Source code for rust-analyzer IDE support
]

# Target platforms
targets = [
    "x86_64-unknown-linux-gnu",    # Primary Linux target for backend services (WSL)
    "wasm32-unknown-unknown",      # WebAssembly target for UI integration
]

# Use default profile (includes rustc, cargo, rust-std)
profile = "default"
