# HoneyLink Development Database Stack
# Deploys TimescaleDB (PostgreSQL 16 + TimescaleDB 2.14) for local development
#
# Usage:
#   docker-compose -f infrastructure/docker-compose.db.yml up -d
#
# Connection String:
#   postgresql://honeylink:dev_password@localhost:5432/honeylink_dev

version: '3.9'

services:
  # TimescaleDB (PostgreSQL 16 + TimescaleDB extension)
  timescaledb:
    image: timescale/timescaledb:2.14.2-pg16
    container_name: honeylink-timescaledb
    restart: unless-stopped
    environment:
      # PostgreSQL superuser credentials (dev only - CHANGE IN PRODUCTION)
      POSTGRES_USER: honeylink
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: honeylink_dev
      # TimescaleDB tuning for development
      TIMESCALEDB_TELEMETRY: 'off'
      # Increase shared memory for better performance
      POSTGRES_SHARED_BUFFERS: '256MB'
      POSTGRES_WORK_MEM: '16MB'
      POSTGRES_MAINTENANCE_WORK_MEM: '128MB'
    ports:
      - "5432:5432"
    volumes:
      # Persist database data
      - timescaledb-data:/var/lib/postgresql/data
      # Auto-run initialization scripts (optional)
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - honeylink-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U honeylink -d honeylink_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=timescaledb"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "log_statement=all"  # Log all SQL (dev only)
      - "-c"
      - "log_duration=on"    # Log query duration

volumes:
  timescaledb-data:
    driver: local

networks:
  honeylink-db:
    driver: bridge
